export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=/usr/local/bin/nvim
export TERMINAL=/usr/bin/konsole
export BROWSER=/usr/bin/chromium
export QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
export WORDCHARS=${WORDCHARS/\*\?\_\-\.\[\]\~\=\/\&\;\!\#\$\%\^\(\)\{\}\<\>} 
export PATH="$PATH:/home/mirsella/.local/bin:/hdd/dev/bin"
hash -d s=/hdd
alias end='sudo pkill -f '
alias rm='s rmtrash -rf '
alias rmf='s /bin/rm -rf '
alias trash-restore='s trash-restore '
alias trash-empty='s trash-empty '
alias trash-list='s trash-list '
alias S='s systemctl '
alias s='sudo -E '
alias chownm='s chown -R $USER: '
alias v='s nvim -p'
