# [".config/nvim/LazyVim"]
# 	type = "git-repo"
#   url = "https://github.com/LazyVim/starter"
#   refreshPeriod = "168h"

# [".config/nvim/autoload/plug.vim"]
#   type = "file"
#   url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
#   refreshPeriod = "168h"

[".config/zsh/.antidote"]
  type = "git-repo"
  url = "https://github.com/mattmc3/antidote"
  clone.args = ["--depth=1"]
  refreshPeriod = "168h"
