keys:
  - &predator-host age17rwehvcpwjw9zycjltvsu0qsnp6vnw9esffzndvm3wrwllezfy8qqwx5uq
  - &laptop age1g7262fjwcagcuu074x439e7jq5wx4hn0smuf94qhv7cy9e4haswslztuzc
  - &main age1rndzt9qrq0u4g3j3fv2fvrjsvg29hf2mc0y64ynt9ajx5pnexvzq6s4utc
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *predator-host
          - *laptop
          - *main
