model = "gpt-5.6-sol"
model_reasoning_effort = "medium"
[projects."/home/mirsella/dev/mightyminions/main"]
trust_level = "trusted"

[projects."/home/mirsella"]
trust_level = "trusted"

[projects."/home/mirsella/Documents/Codex/2026-07-12/com"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 2

[marketplaces.openai-bundled]
last_updated = "2026-07-12T16:43:46Z"
source_type = "local"
source = "/home/mirsella/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-12T07:49:09Z"
source_type = "local"
source = "/home/mirsella/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[features]
js_repl = false
memories = true

[mcp_servers.node_repl]
args = []
command = "/opt/codex-desktop/resources/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = ""
NODE_REPL_NODE_PATH = "/opt/codex-desktop/resources/node-runtime/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/home/mirsella/.codex"
CODEX_HOME = "/home/mirsella/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f,e74b67ab909392b37f7aef14977fce7aa80cfa02ade5491f30abcdbcb9e69f33,a8c5d0b9ca9076003dac7313a7cc4c7e9210e2e1094b5108c35f0f478e64794a,d75ac3ac5a6bf4f5e010fb12cc718572c02d3ddb503ce9c4fc82102c565fe799"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.707.51957"

[mcp_servers.node_repl.tools]

[mcp_servers.node_repl.tools.js]
approval_mode = "approve"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
env_http_headers = { "CONTEXT7_API_KEY" = "CONTEXT7_API_KEY" }

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = false
followUpQueueMode = "queue"

[plugins."browser@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled".mcp_servers.computer-use.tools.press_key]
approval_mode = "approve"

[plugins."computer-use@openai-bundled".mcp_servers.computer-use.tools.type_text]
approval_mode = "approve"

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true
