worker_processes  auto;
events {
	worker_connections  4000;
	use epoll;
	multi_accept on;
}

error_log /var/log/nginx/error.log;

http {
	# include sites-enabled/mirsella.conf;
  include sites-enabled/git.mirsella.conf;
  include sites-enabled/ssh.mirsella.conf;
  include sites-enabled/vnc.mirsella.conf;
  include sites-enabled/site.mirsella.conf;
}
