worker_processes  auto;
events {
	worker_connections  4000;
	use epoll;
	multi_accept on;
}

error_log /var/log/nginx/error.log;

http {
  server {
    listen 80 default_server;
    server_name mirsella.mooo.com mirsella.fr.to;
    return 301 https://$host$request_uri/;

  }

  server {
    listen 443 ssl default_server;
    server_name mirsella.mooo.com mirsella.fr.to;
    include sites-enabled/ssl.conf;

    location /git/ {
      proxy_pass https://127.0.0.1:4440/;
    }
    location /ssh/ {
      proxy_pass https://127.0.0.1:4460/;
      proxy_http_version 1.1;
      proxy_read_timeout 300;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Real-PORT $remote_port;
    }
    location /vnc/ {
      proxy_pass https://127.0.0.1:4470/;
    }
  }
}
