#I will post my file 


extra-keys = [ \
             ['=',   '{',    '}',   '[',    ']',    '(',     ')',    '*'],   \
             ['ESC', '-',    '/',   'HOME', 'UP',   'END',   '"',    'DEL'], \
             ['TAB', 'CTRL', 'ALT', 'LEFT', 'DOWN', 'RIGHT', '~', 'BKSP'] \
] extra-keys = [['ESC','/','BACKSLASH','|','HOME','UP','END','PGUP'],['TAB','CTRL','$','~','LEFT','DOWN','RIGHT','PGDN']]

