shell = "tmux"
import = ["~/.config/alacritty/rose-pine-moon.toml"]
live_config_reload = true

[window]
startup_mode = "Maximized"

[scrolling]
history = 100000

[font]
size = 17.0
normal = { family = "JetBrainsMono Nerd Font", style = "Normal" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
