server {
	listen 80;
	server_name git.mirsella.mooo.com;
  return 301 https://$host$request_uri;
}
  
server {
    listen 443 ssl;
    server_name git.mirsella.mooo.com;
    include sites-enabled/ssl.conf;
    location / {
      proxy_pass https://127.0.0.1:4440;
    }
}
