server {
	listen 80 default_server;
	server_name mirsella.mooo.com;
	return 301 https://$host$request_uri;
	location /http {
		root /hdd/www/html/mirsella.mooo.com;
		index index.html;
    }
}
    
server {
	include sites-enabled/mirsella_ssl.conf;
	include sites-enabled/ssh.conf;
	location / {
		root /hdd/www/html/mirsella.mooo.com;
		index index.html;
	}
}
