server {
	listen 80;
	server_name site.mirsella.mooo.com;
	return 301 https://$host$request_uri;
  location /http {
		root /hdd/www/html/snt;
		index index.html;
  }
}
    
server {
	listen 443 ssl;
  server_name site.mirsella.mooo.com;
	include sites-enabled/ssl.conf;
	location / {
		root /hdd/www/html/snt;
		index index.html;
	}
}
