server {
  listen 80;
  server_name ssh.mirsella.mooo.com;
  return 301 https://$host$request_uri;
  location /http {
    proxy_pass http://127.0.0.1:8500/;
    proxy_http_version 1.1;
    proxy_read_timeout 300;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Real-PORT $remote_port;
  }
}

server {
    listen 443 ssl;
    server_name ssh.mirsella.mooo.com;
    include sites-enabled/ssl.conf;
    location / {
      proxy_pass https://127.0.0.1:4450/;
      proxy_http_version 1.1;
      proxy_read_timeout 300;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Real-PORT $remote_port;
    }
}
