server {
  listen 80;
  server_name vnc.mirsella.mooo.com;
  return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name vnc.mirsella.mooo.com;
    include sites-enabled/ssl.conf;
    location /websockify {
          proxy_http_version 1.1;
          proxy_pass http://127.0.0.1:4460/;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";

          # VNC connection timeout
          proxy_read_timeout 61s;

          # Disable cache
          proxy_buffering off;
    }

    location / {
          index vnc.html;
          alias /hdd/www/novnc/;
          try_files $uri $uri/ /vnc.html;
    }
}
