# Generated by nixos-generate-config on main. Put policy changes in default.nix.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/18dc205e-4518-49a0-b693-290f81634fef";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/18dc205e-4518-49a0-b693-290f81634fef";
      fsType = "btrfs";
      options = [ "subvol=@.snapshots" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/18dc205e-4518-49a0-b693-290f81634fef";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/cache/pacman/pkg" =
    { device = "/dev/disk/by-uuid/18dc205e-4518-49a0-b693-290f81634fef";
      fsType = "btrfs";
      options = [ "subvol=@pkg" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/18dc205e-4518-49a0-b693-290f81634fef";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3613-BAFF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
