return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "stylua",
      "shellcheck",
      "vue-language-server",
      "clangd",
      "dockerfile-language-server",
      "docker-compose-language-service",
      "emmet-language-server",
      "json-lsp",
      "lua-language-server",
      "markdowlint",
      "marksman",
      "prettier",
      "pyright",
      "rust-analyzer",
      "shfmt",
      "tailwind-language-server",
      "taplo",
      "typescript-language-server",
      "yaml-language-server",
    },
  },
}
