encryption = "age"

[age]
	identity = "~/.ssh/id_ed25519"
	recipients = [
		"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGkl0CiN6/cLz1OOzBvHaPAMKTnYI0sOlKFDRW25uReF",
		"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMXuc6N//8+RfjUhuRZ+COgynjfwFqAeoKAWMUz6s+Pe",
	]

[git]
	autoCommit = true
	autoPush = true
