ANDROID_HOME=${XDG_DATA_HOME}/android/sdk
ANDROID_SDK_ROOT=${ANDROID_HOME}
ANDROID_AVD_HOME=${XDG_DATA_HOME}/android/avd
ANDROID_USER_HOME=${XDG_CONFIG_HOME}/android
ANDROID_EMULATOR_HOME=${ANDROID_USER_HOME}
ANDROID_NDK_HOME=${ANDROID_HOME}/ndk/27.0.12077973
ANDROID_NDK_ROOT=${ANDROID_NDK_HOME}
NDK_HOME=${ANDROID_NDK_HOME}
