GRADLE_USER_HOME=${XDG_DATA_HOME}/gradle
CARGO_HOME=${XDG_DATA_HOME}/cargo
RUSTUP_HOME=${XDG_DATA_HOME}/rustup
GOPATH=${XDG_DATA_HOME}/go
CUDA_PATH=/opt/cuda
CUDA_CACHE_PATH=${XDG_CACHE_HOME}/nv
GEM_HOME=${XDG_DATA_HOME}/gem
GEM_SPEC_CACHE=${XDG_CACHE_HOME}/gem
_JAVA_OPTIONS=-Djava.util.prefs.userRoot=${XDG_CONFIG_HOME}/java
PSQLRC=${XDG_CONFIG_HOME}/pg/psqlrc
PSQL_HISTORY=${XDG_STATE_HOME}/psql_history
PGPASSFILE=${XDG_CONFIG_HOME}/pg/pgpass
PGSERVICEFILE=${XDG_CONFIG_HOME}/pg/pg_service.conf
DUB_HOME=${XDG_CACHE_HOME}/dub
JAVA_HOME=/usr/lib/jvm/default
CAPACITOR_ANDROID_STUDIO_PATH=/usr/bin/android-studio
ANSIBLE_HOME=${XDG_CONFIG_HOME}/ansible
ANSIBLE_CONFIG=${XDG_CONFIG_HOME}/ansible.cfg
ANSIBLE_GALAXY_CACHE_DIR=${XDG_CACHE_HOME}/ansible/galaxy_cache
PNPM_HOME=${XDG_DATA_HOME}/pnpm
WASMER_DIR=${XDG_CONFIG_HOME}/wasmer
WASMER_CACHE_DIR=${XDG_CACHE_HOME}/wasmer
