OPENCODE_EXPERIMENTAL_EXA=1
OPENCODE_EXPERIMENTAL_LSP_TOOL=1
OPENCODE_EXPERIMENTAL_ICON_DISCOVERY=1
OPENCODE_EXPERIMENTAL_FILEWATCHER=1
OPENCODE_EXPERIMENTAL_EVENT_SYSTEM=1
OPENCODE_EXPERIMENTAL_WORKSPACES=1
