title   Arch Linux (linux-cachyos)
linux   /vmlinuz-linux-cachyos
initrd  /initramfs-linux-cachyos.img
options root=PARTUUID=6387f161-23d7-4098-8662-896c8b43fda8 rootflags=subvol=@ rw rootfstype=btrfs video.use_native_backlight=1 usbcore.quirks=0x1d6b:0x0003:i resume=UUID=18dc205e-4518-49a0-b693-290f81634fef resume_offset=272657282 zswap.enabled=0
sort-key 1
